name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: Lint files
        run: deno lint
      - name: Check formatting
        run: deno fmt --check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.x, canary]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run unit tests on Deno
        run: deno test
      - uses: actions/setup-node@v2
      - name: Build and run unit tests on the npm version
        run: deno run -A ./scripts/build_npm.ts

