name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Check formatting
        run: deno fmt --check **/*.ts
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.x, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run unit tests on Deno
        run: deno test
      - uses: actions/setup-node@v2
      - name: Build and run unit tests on the npm version
        run: deno run -A ./scripts/build_npm.ts

